[custom.all.idris2-Multiset-Intermediate]
type = "local"
path = "."
ipkg = "idris2-Multiset-Intermediate.ipkg"
test = "idris2-Multiset-Intermediate-tests/idris2-Multiset-Intermediate-test.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
