project:
  type: book
  output-dir: _book

book:
  title: "YAQT"
  subtitle: "Yet Another Quantum Theory"
  author: "Justin Kelly"
  chapters:
    - index.qmd
    - idris2-base.qmd

format:
  orange-book-typst:
    template-partials:
      - typst-show.typ
    keep-typ: true
    cover: "orange-book/background.svg"
    image-index: "orange-book/orange1.jpg"

bibliography: references.bib
