[custom.all.idris2-Singletons-Pixels-and-Maxels]
type = "local"
path = "."
ipkg = "idris2-Singletons-Pixels-and-Maxels.ipkg"
test = "idris2-Singletons-Pixels-and-Maxels-tests/idris2-Singletons-Pixels-and-Maxels-test.ipkg"

[custom.all.idris2-Multiset-Basic]
type = "local"
path = "../idris2-Multiset-Basic"
ipkg = "idris2-Multiset-Basic.ipkg"
